#!/bin/bash

cd /home/texec/srt_files

echo "" > last_log
./get_subtitle_files_from_amara >> last_log 2>>last_log
./fix_files >> last_log
./upload_subtitles >> last_log 2>>last_log
git add *.srt >> last_log 2>>last_log
git commit -m "update from amara" >> last_log 2>>last_log
